global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['monitoring:9090']
  - job_name: 'kafka-hosts'
    static_configs:
    - targets: ['192.168.99.101:9100']
    - targets: ['192.168.99.102:9100']
    - targets: ['192.168.99.103:9100']
  - job_name: 'kafka-jmx'
    static_configs:
    - targets: ['192.168.99.101:9101']
    - targets: ['192.168.99.102:9101']
    - targets: ['192.168.99.103:9101']
